// <auto-generated />
using System;
using EducareBE.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EducareBE.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221126184623_test")]
    partial class test
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EducareBE.Models.Entities.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("FieldId")
                        .HasColumnType("int");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FieldId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FieldId = 2,
                            IsFavorite = false,
                            Name = "POO",
                            Year = 2
                        },
                        new
                        {
                            Id = 2,
                            FieldId = 2,
                            IsFavorite = false,
                            Name = "SDA",
                            Year = 2
                        },
                        new
                        {
                            Id = 3,
                            FieldId = 2,
                            IsFavorite = false,
                            Name = "TD",
                            Year = 4
                        });
                });

            modelBuilder.Entity("EducareBE.Models.Entities.EnrolledCourses", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsEnrolled")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsFavoirte")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("UserId");

                    b.ToTable("EnrolledCourses");
                });

            modelBuilder.Entity("EducareBE.Models.Entities.Faculty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UniversityId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UniversityId");

                    b.ToTable("Faculties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Automation And Computers",
                            UniversityId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Electronics and Telecomunication",
                            UniversityId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Faculty Of Managemen And Transportation ",
                            UniversityId = 1
                        },
                        new
                        {
                            Id = 4,
                            Name = "Faculty of Mechanical Engineerin",
                            UniversityId = 1
                        },
                        new
                        {
                            Id = 5,
                            Name = "Faculty of Finance and Banking",
                            UniversityId = 2
                        });
                });

            modelBuilder.Entity("EducareBE.Models.Entities.Field", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("FacultyId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FacultyId");

                    b.ToTable("Fields");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FacultyId = 1,
                            Name = "Informatics"
                        },
                        new
                        {
                            Id = 2,
                            FacultyId = 1,
                            Name = "Computers and Information Technology"
                        },
                        new
                        {
                            Id = 3,
                            FacultyId = 2,
                            Name = "Informatics"
                        });
                });

            modelBuilder.Entity("EducareBE.Models.Entities.Like", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("DislikesCount")
                        .HasColumnType("int");

                    b.Property<int>("LikesCount")
                        .HasColumnType("int");

                    b.Property<int>("SubjectAddedById")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubjectAddedById");

                    b.HasIndex("UserId");

                    b.ToTable("Likes");
                });

            modelBuilder.Entity("EducareBE.Models.Entities.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("FacultyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfLikes")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfPosts")
                        .HasColumnType("int");

                    b.Property<int>("StudyYear")
                        .HasColumnType("int");

                    b.Property<string>("UniversityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("EducareBE.Models.Entities.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseId = 1,
                            Name = "Objects and Classes"
                        },
                        new
                        {
                            Id = 2,
                            CourseId = 1,
                            Name = "Polymorphism"
                        },
                        new
                        {
                            Id = 3,
                            CourseId = 1,
                            Name = "Errors"
                        });
                });

            modelBuilder.Entity("EducareBE.Models.Entities.SubjectAddedBy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SubjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.ToTable("SubjectsAddedBy");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Objects",
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Classes",
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "ClassesMaterial",
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 4,
                            Name = "Poly",
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 5,
                            Name = "ErrorMaterial",
                            SubjectId = 3
                        });
                });

            modelBuilder.Entity("EducareBE.Models.Entities.University", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalExercices")
                        .HasColumnType("int");

                    b.Property<int>("TotalFields")
                        .HasColumnType("int");

                    b.Property<int>("TotalSubjects")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Universities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Polytechnic University of Timisoara",
                            TotalExercices = 0,
                            TotalFields = 0,
                            TotalSubjects = 0
                        },
                        new
                        {
                            Id = 2,
                            Name = "Vest University of Timisoara",
                            TotalExercices = 0,
                            TotalFields = 0,
                            TotalSubjects = 0
                        },
                        new
                        {
                            Id = 3,
                            Name = "Vest University of Timisoara",
                            TotalExercices = 0,
                            TotalFields = 0,
                            TotalSubjects = 0
                        },
                        new
                        {
                            Id = 4,
                            Name = "Standford University",
                            TotalExercices = 0,
                            TotalFields = 0,
                            TotalSubjects = 0
                        },
                        new
                        {
                            Id = 5,
                            Name = "Massachusetts Institute of Technology",
                            TotalExercices = 0,
                            TotalFields = 0,
                            TotalSubjects = 0
                        });
                });

            modelBuilder.Entity("EducareBE.Models.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EducareBE.Models.Entities.Course", b =>
                {
                    b.HasOne("EducareBE.Models.Entities.Field", "Field")
                        .WithMany("Courses")
                        .HasForeignKey("FieldId");

                    b.Navigation("Field");
                });

            modelBuilder.Entity("EducareBE.Models.Entities.EnrolledCourses", b =>
                {
                    b.HasOne("EducareBE.Models.Entities.Course", "Course")
                        .WithMany("EnrolledCourses")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EducareBE.Models.Entities.User", "User")
                        .WithMany("EnrolledCourses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EducareBE.Models.Entities.Faculty", b =>
                {
                    b.HasOne("EducareBE.Models.Entities.University", "University")
                        .WithMany("Faculties")
                        .HasForeignKey("UniversityId");

                    b.Navigation("University");
                });

            modelBuilder.Entity("EducareBE.Models.Entities.Field", b =>
                {
                    b.HasOne("EducareBE.Models.Entities.Faculty", "Faculty")
                        .WithMany("Fields")
                        .HasForeignKey("FacultyId");

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("EducareBE.Models.Entities.Like", b =>
                {
                    b.HasOne("EducareBE.Models.Entities.SubjectAddedBy", "SubjectAddedBy")
                        .WithMany("Likes")
                        .HasForeignKey("SubjectAddedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EducareBE.Models.Entities.User", "User")
                        .WithMany("Likes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubjectAddedBy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EducareBE.Models.Entities.Profile", b =>
                {
                    b.HasOne("EducareBE.Models.Entities.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("EducareBE.Models.Entities.Profile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EducareBE.Models.Entities.Subject", b =>
                {
                    b.HasOne("EducareBE.Models.Entities.Course", "Course")
                        .WithMany("Subjects")
                        .HasForeignKey("CourseId");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("EducareBE.Models.Entities.SubjectAddedBy", b =>
                {
                    b.HasOne("EducareBE.Models.Entities.Subject", "Subject")
                        .WithMany("SubjectsAddedBy")
                        .HasForeignKey("SubjectId");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("EducareBE.Models.Entities.Course", b =>
                {
                    b.Navigation("EnrolledCourses");

                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("EducareBE.Models.Entities.Faculty", b =>
                {
                    b.Navigation("Fields");
                });

            modelBuilder.Entity("EducareBE.Models.Entities.Field", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("EducareBE.Models.Entities.Subject", b =>
                {
                    b.Navigation("SubjectsAddedBy");
                });

            modelBuilder.Entity("EducareBE.Models.Entities.SubjectAddedBy", b =>
                {
                    b.Navigation("Likes");
                });

            modelBuilder.Entity("EducareBE.Models.Entities.University", b =>
                {
                    b.Navigation("Faculties");
                });

            modelBuilder.Entity("EducareBE.Models.Entities.User", b =>
                {
                    b.Navigation("EnrolledCourses");

                    b.Navigation("Likes");

                    b.Navigation("Profile")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
